version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=packaging_supply_system
      - DB_SYNCHRONIZE=false
      - DB_LOGGING=false
      - JWT_SECRET=your-production-jwt-secret-here
      - JWT_EXPIRES_IN=1d
    depends_on:
      - db
    container_name: app-prod
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=packaging_supply_system
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    container_name: db-prod
    restart: unless-stopped
    ports:
      - '5432:5432'

volumes:
  db_data_prod:
