services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - JWT_SECRET=SUPER_SECRET_KEY
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: packaging_supply_system
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
