version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=packaging_supply_system
      - DB_SYNCHRONIZE=false
      - DB_LOGGING=false
      - JWT_SECRET=your-production-jwt-secret-here
      - JWT_EXPIRES_IN=1d
    container_name: app-prod
    restart: unless-stopped
